version: '3'
services:
  react_app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
      # ^^ weird looking command: map . (this directory) to /app inside the container.
    # set environment variables:
    environment:
      - CHOKIDAR_USEPOLLING=true
  test_app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
      # ^^ weird looking command: map . (this directory) to /app inside the container.
    # set environment variables:
    environment:
      - CHOKIDAR_USEPOLLING=true
    # override starting command:
    command: ["npm", "run", "test"]